# Generated by Django 2.0.6 on 2018-06-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0005_auto_20180611_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='name',
            new_name='created_by',
        ),
    ]
