# Generated by Django 2.0.6 on 2018-06-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0006_auto_20180611_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='created_by',
            new_name='name',
        ),
    ]
