# Generated by Django 2.0.6 on 2018-06-11 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0007_auto_20180611_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='name',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fb.Members'),
        ),
    ]
