# Generated by Django 2.0.6 on 2018-06-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0008_auto_20180611_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='pic',
        ),
        migrations.AddField(
            model_name='notifications',
            name='member',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb.Members'),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='name',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb.Members'),
        ),
    ]
