# Generated by Django 2.0.6 on 2018-06-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0009_auto_20180612_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='content',
            field=models.TextField(),
        ),
    ]
