# Generated by Django 2.0.6 on 2018-06-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0011_auto_20180612_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fb.Members'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='timeline',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fb.Timeline'),
        ),
    ]
