# Generated by Django 2.0.6 on 2018-06-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0012_auto_20180612_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
