# Generated by Django 2.0.6 on 2018-06-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0013_auto_20180612_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
