# Generated by Django 2.0.6 on 2018-06-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0014_auto_20180612_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb.Members'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='timeline',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb.Timeline'),
        ),
    ]
