# Generated by Django 2.0.6 on 2018-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0015_auto_20180612_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsReq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=25)),
                ('pic', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'friendsreq',
            },
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('pic', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'markets',
            },
        ),
    ]
